name: teoria_forum_mobile
description: Cliente Flutter para explorar y debatir teorías desde la plataforma Teoría.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.1.0
  collection: ^1.18.0
  go_router: ^14.2.1
  flutter_colorpicker: ^1.0.3
  flutter_html: ^3.0.0
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  image_picker: ^1.0.7
  mime: ^1.0.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
